version: '3.8'

volumes:
  data_vol:

services:
  database:
    image: mysql:8.0.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - data_vol:/var/lib/mysql
    restart: always

  web:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=mysql
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - database
